title: A Tutorial for Phylogenetic Analyses in Jupyter Notebook
logo: "/images/joker_logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  ### Steps to creating phylogenetic trees 
  1. Download sequence data
  2. Align sequence data
  3. Create Phylogenetic Tree
  4. Run statistical analyses 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
